libdot: require Python 3.5+ up front
We're only testing against Python 3.5 or newer currently, and we're
using features added in that release, so make we're running it.  This
will help avoid confusing errors like:
  File ".../libapps/libdot/bin/libdot.py", line 135, in run
    result = subprocess.run(cmd, cwd=cwd, **kwargs)
AttributeError: 'module' object has no attribute 'run'

Change-Id: I1e31ad04faf85dc7e94606e8106973f1fe950f2d
Reviewed-on: https://chromium-review.googlesource.com/c/apps/libapps/+/1660837
Reviewed-by: Joel Hockey <joelhockey@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>